/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;


/**
 *
 * @author ASUS
 */
public class frmPrincipal extends javax.swing.JFrame {
    private String rolUsuario;
    /**
     * Creates new form frmPrincipal
     * @param rol
     */
    public frmPrincipal(String rol) {
        initComponents();
        this.rolUsuario = rol;
        
        aplicarPermisosPorRol();
        // ¡Esta línea centra la ventana en la pantalla!
        this.setLocationRelativeTo(null);
        
    }
    private void aplicarPermisosPorRol() {
    if (rolUsuario.equals("Asesor de Viaje")) {
        mnAdministracion.setVisible(false);
        mnOperaciones.setVisible(false);
    } 
    else if (rolUsuario.equals("Operador")) {
        mnAdministracion.setVisible(false);
        mnVentas.setVisible(false);
        menuReportes.setVisible(false);
    }
 }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        MenubarPrincipal = new javax.swing.JMenuBar();
        mnAdministracion = new javax.swing.JMenu();
        mnitemGestionarEmpleados = new javax.swing.JMenuItem();
        mnitemGestionarDestinos = new javax.swing.JMenuItem();
        mnitemGestionarPaquetes = new javax.swing.JMenuItem();
        mnitemPromocionesDescuentos = new javax.swing.JMenuItem();
        mnVentas = new javax.swing.JMenu();
        mnOperaciones = new javax.swing.JMenu();
        mnitemItinerario = new javax.swing.JMenuItem();
        mnitemCupos = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        mnitemReservasPaquete = new javax.swing.JMenuItem();
        mnitemDestinosSolicitados = new javax.swing.JMenuItem();
        mnitemIngresosPorAsesor = new javax.swing.JMenuItem();
        mnitemClienteconDeuda = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        mnitmCerrarsesion = new javax.swing.JMenuItem();
        mnitmSalir = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnAdministracion.setText("Administración");

        mnitemGestionarEmpleados.setText("Gestionar Empleados");
        mnitemGestionarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemGestionarEmpleadosActionPerformed(evt);
            }
        });
        mnAdministracion.add(mnitemGestionarEmpleados);

        mnitemGestionarDestinos.setText("Gestionar Destinos");
        mnAdministracion.add(mnitemGestionarDestinos);

        mnitemGestionarPaquetes.setText("Gestionar Paquetes Turísticos");
        mnAdministracion.add(mnitemGestionarPaquetes);

        mnitemPromocionesDescuentos.setText("Promociones y Descuentos ");
        mnAdministracion.add(mnitemPromocionesDescuentos);

        MenubarPrincipal.add(mnAdministracion);

        mnVentas.setText("Ventas");
        MenubarPrincipal.add(mnVentas);

        mnOperaciones.setText("Operaciones");

        mnitemItinerario.setText("Itinerario");
        mnOperaciones.add(mnitemItinerario);

        mnitemCupos.setText("Control de Cupos");
        mnOperaciones.add(mnitemCupos);

        MenubarPrincipal.add(mnOperaciones);

        menuReportes.setText("Reportes");

        mnitemReservasPaquete.setText("Reservas por Paquete");
        mnitemReservasPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemReservasPaqueteActionPerformed(evt);
            }
        });
        menuReportes.add(mnitemReservasPaquete);

        mnitemDestinosSolicitados.setText("Destinos más solicitados");
        menuReportes.add(mnitemDestinosSolicitados);

        mnitemIngresosPorAsesor.setText("Ingresos por Asesor");
        menuReportes.add(mnitemIngresosPorAsesor);

        mnitemClienteconDeuda.setText("Cliente con Deuda");
        menuReportes.add(mnitemClienteconDeuda);

        MenubarPrincipal.add(menuReportes);

        mnSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sistema-de-escritorio.png"))); // NOI18N
        mnSistema.setText("Sistema");

        mnitmCerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        mnitmCerrarsesion.setText("Cerrar sesión");
        mnitmCerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmCerrarsesionActionPerformed(evt);
            }
        });
        mnSistema.add(mnitmCerrarsesion);

        mnitmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SalirSistema.png"))); // NOI18N
        mnitmSalir.setText("Salir del sistema");
        mnitmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmSalirActionPerformed(evt);
            }
        });
        mnSistema.add(mnitmSalir);

        MenubarPrincipal.add(mnSistema);

        setJMenuBar(MenubarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmSalirActionPerformed
                                          
    // 1. Creamos una ventana emergente temporal (JDialog) vinculada al formulario principal
    final javax.swing.JDialog ventanaAlerta = new javax.swing.JDialog(this, "Saliendo", true);
    
    // 2. Le quitamos los bordes y botones de cerrar (X) para que se vea minimalista y limpio
    ventanaAlerta.setUndecorated(true);
    
    // 3. Creamos una etiqueta de texto con un diseño elegante
    javax.swing.JLabel txtMensaje = new javax.swing.JLabel(
        "<html><center><font size='5' color='#0f2a4a'><b>Legacy Travel</b></font><br>"
        + "<font size='4' color='#555555'>Cerrando el sistema de forma segura...<br>Espere un momento.</font></center></html>", 
        javax.swing.JLabel.CENTER
    );
    
    // 4. Configuramos el contenedor de la alerta (Fondo blanco y margen)
    txtMensaje.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30));
    ventanaAlerta.getContentPane().setBackground(java.awt.Color.WHITE);
    ventanaAlerta.getContentPane().add(txtMensaje);
    
    // Le ponemos un borde exterior gris muy fino para que resalte
    ((javax.swing.JComponent)ventanaAlerta.getContentPane()).setBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1)
    );

    // 5. Ajustamos el tamaño automáticamente según el texto y lo centramos en la pantalla
    ventanaAlerta.pack();
    ventanaAlerta.setLocationRelativeTo(this);

    // 6. Creamos el temporizador de 3 segundos (3000 ms) para que cierre la alerta y apague el programa
    javax.swing.Timer temporizador = new javax.swing.Timer(3000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            ventanaAlerta.dispose(); // Cierra y destruye el mensaje flotante
            System.exit(0);         // Cierra por completo toda la aplicación
        }
    });
    temporizador.setRepeats(false);
    temporizador.start(); // Inicia la cuenta regresiva de los 3 segundos

    // 7. Hacemos visible el mensaje flotante (bloquea la pantalla trasera mientras cuenta el tiempo)
    ventanaAlerta.setVisible(true);
    }//GEN-LAST:event_mnitmSalirActionPerformed

    private void mnitmCerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmCerrarsesionActionPerformed
        // TODO add your handling code here:
        // 1. Creamos la ventana emergente flotante (JDialog) vinculada al formulario principal
        final javax.swing.JDialog alertaCierre = new javax.swing.JDialog(this, "Cerrando Sesión", true);
        
        // 2. Le quitamos los bordes y la 'X' para que se vea minimalista
        alertaCierre.setUndecorated(true);

        // 3. Diseñamos el mensaje elegante en HTML
        javax.swing.JLabel txtMensaje = new javax.swing.JLabel(
            "<html><center><font size='5' color='#0f2a4a'><b>Legacy Travel</b></font><br>"
            + "<font size='4' color='#555555'>Cerrando sesión de forma segura...<br>Redireccionando al Login.</font></center></html>", 
            javax.swing.JLabel.CENTER
        );

        // 4. Configuramos el contenedor (Fondo blanco, márgenes y borde fino gris)
        txtMensaje.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30));
        alertaCierre.getContentPane().setBackground(java.awt.Color.WHITE);
        alertaCierre.getContentPane().add(txtMensaje);

        ((javax.swing.JComponent)alertaCierre.getContentPane()).setBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1)
        );

        // 5. Ajustamos tamaño y centramos en pantalla
        alertaCierre.pack();
        alertaCierre.setLocationRelativeTo(this);

        // Ocultamos la ventana principal de inmediato para un efecto de salida limpio
        this.setVisible(false);

        // 6. Creamos el temporizador de 3 segundos (3000 ms)
        javax.swing.Timer temporizador = new javax.swing.Timer(3000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                alertaCierre.dispose();      // Destruye el letrero flotante de la pantalla
                frmPrincipal.this.dispose(); // Libera por completo la memoria de la ventana principal
                
                // 7. Abrimos la ventana de Login fresca y centrada
                frmLogin ventanaLogin = new frmLogin();
                ventanaLogin.setVisible(true);
                ventanaLogin.setLocationRelativeTo(null);
            }
        });
        
        temporizador.setRepeats(false);
        temporizador.start(); // ¡Inicia la cuenta regresiva!

        // Hacemos visible la alerta (se queda congelada los 3 segundos del contador)
        alertaCierre.setVisible(true);   
    }//GEN-LAST:event_mnitmCerrarsesionActionPerformed

    private void mnitemReservasPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemReservasPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnitemReservasPaqueteActionPerformed

    private void mnitemGestionarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemGestionarEmpleadosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnitemGestionarEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }//</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenubarPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu mnAdministracion;
    private javax.swing.JMenu mnOperaciones;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenu mnVentas;
    private javax.swing.JMenuItem mnitemClienteconDeuda;
    private javax.swing.JMenuItem mnitemCupos;
    private javax.swing.JMenuItem mnitemDestinosSolicitados;
    private javax.swing.JMenuItem mnitemGestionarDestinos;
    private javax.swing.JMenuItem mnitemGestionarEmpleados;
    private javax.swing.JMenuItem mnitemGestionarPaquetes;
    private javax.swing.JMenuItem mnitemIngresosPorAsesor;
    private javax.swing.JMenuItem mnitemItinerario;
    private javax.swing.JMenuItem mnitemPromocionesDescuentos;
    private javax.swing.JMenuItem mnitemReservasPaquete;
    private javax.swing.JMenuItem mnitmCerrarsesion;
    private javax.swing.JMenuItem mnitmSalir;
    // End of variables declaration//GEN-END:variables
}

