/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;
import Clases.DestinosTuristicos;
import javax.swing.table.DefaultTableModel;
import Gestion.GestionDestinoTuristico;


/**
 *
 * @author Piero
 */
public class frmDestinos extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private Gestion.GestionDestinoTuristico gestionDestino;

    /**
     * Creates new form frmDestinos
     */
    public frmDestinos(GestionDestinoTuristico gestionDestino) {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("ID Destino");
        modelo.addColumn("Nombre");
        modelo.addColumn("País");
        modelo.addColumn("Ciudad");
        
        
        jTable1.setModel(modelo);
        
        
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        this.gestionDestino = gestionDestino;
        cargarDestinosPrueba();
        listarDestinos();
    }
    private void cargarDestinosPrueba() {
        
        if (gestionDestino.getContador() == 0) {
            DestinosTuristicos d1 = new DestinosTuristicos("D001", "Machu Picchu", "Perú", "Cusco", 
                    "Maravilla del mundo antiguo", "Templado-Subtropical", "Español/Quechua", "machupicchu.jpg");
                    
            DestinosTuristicos d2 = new DestinosTuristicos("D002", "Torre Eiffel", "Francia", "París", 
                    "Monumento icónico de Europa", "Templado", "Francés", "eiffel.jpg");
                    
            DestinosTuristicos d3 = new DestinosTuristicos("D003", "Estatua de la Libertad", "EEUU", "Nueva York", 
                    "Monumento representativo e histórico", "Continental", "Inglés", "libertad.jpg");

            gestionDestino.registrarDestino(d1);
            gestionDestino.registrarDestino(d2);
            gestionDestino.registrarDestino(d3);
        }
    }
    void listarDestinos() {
        modelo.setNumRows(0);
        
        for (int i = 0; i < gestionDestino.getContador(); i++) {
            Object[] fila = {
                gestionDestino.getListaDestinos()[i].getIdDestino(),
                gestionDestino.getListaDestinos()[i].getNombre(),
                gestionDestino.getListaDestinos()[i].getPais(),
                gestionDestino.getListaDestinos()[i].getCiudad()
            };
            modelo.addRow(fila);
        }
    }

    void limpiar() {
        txtId.setText("");
        txtNombre.setText("");
        txtPais.setText("");
        txtCiudad.setText("");
        txtDescripcion.setText("");
        txtClima.setText("");
        txtIdioma.setText("");
        txtImagen.setText("");
        txtId.requestFocus();
    }
    void navegar() {
        int fila = jTable1.getSelectedRow();
        if (fila != -1) { 
            txtId.setText("" + jTable1.getValueAt(fila, 0));
            txtNombre.setText("" + jTable1.getValueAt(fila, 1));
            txtPais.setText("" + jTable1.getValueAt(fila, 2));
            txtCiudad.setText("" + jTable1.getValueAt(fila, 3));
            
            String id = "" + jTable1.getValueAt(fila, 0);
            DestinosTuristicos obj = gestionDestino.buscarPorId(id);
            if (obj != null) {
                txtDescripcion.setText(obj.getDescripción()); 
                txtClima.setText(obj.getClima());
                txtIdioma.setText(obj.getIdioma());
                txtImagen.setText(obj.getImagen());
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelId = new javax.swing.JLabel();
        jlabelNombre = new javax.swing.JLabel();
        jlabelPais = new javax.swing.JLabel();
        jlabelCiudad = new javax.swing.JLabel();
        jlabelDescripcion = new javax.swing.JLabel();
        jlabelClima = new javax.swing.JLabel();
        jlabelIdioma = new javax.swing.JLabel();
        jlabelImagen = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtClima = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtImagen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabelId.setText("ID Destino");

        jlabelNombre.setText("Nombre");

        jlabelPais.setText("Pais");

        jlabelCiudad.setText("Ciudad");

        jlabelDescripcion.setText("Descripcion");

        jlabelClima.setText("Clima");

        jlabelIdioma.setText("Idioma");

        jlabelImagen.setText("Imagen");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Destino", "Nombre", "Pais", "Ciudad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(btnModificar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(btnEliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRegistrar)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnBuscar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jlabelClima, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlabelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(199, 199, 199)
                                                .addComponent(jlabelIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlabelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(187, 187, 187)
                                                .addComponent(jlabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClima, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabelId)
                            .addComponent(jlabelDescripcion)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabelNombre)
                            .addComponent(jlabelClima)
                            .addComponent(txtClima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelPais)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabelIdioma)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelCiudad)
                    .addComponent(jlabelImagen)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
                                                   
        String id = txtId.getText().trim();
        String nombre = txtNombre.getText().trim();
        String pais = txtPais.getText().trim();
        String ciudad = txtCiudad.getText().trim();
        String descripcion = txtDescripcion.getText().trim();
        String clima = txtClima.getText().trim();
        String idioma = txtIdioma.getText().trim();
        String imagen = txtImagen.getText().trim();
        
        
        if (id.isEmpty() || nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete al menos el ID y el Nombre del destino.");
            return;
        }
        
       
        DestinosTuristicos destino = new DestinosTuristicos(id, nombre, pais, ciudad, descripcion, clima, idioma, imagen);
        
        if (gestionDestino.registrarDestino(destino)) {
            listarDestinos();
            limpiar();
            javax.swing.JOptionPane.showMessageDialog(this, "Destino registrado con éxito");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar, almacenamiento lleno");
        }
    
      
        
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText().trim();
        if (gestionDestino.eliminarDestino(id)) {
            listarDestinos();
            limpiar();
            javax.swing.JOptionPane.showMessageDialog(this, "Destino eliminado con éxito");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el destino a eliminar");
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText().trim();
String nombre = txtNombre.getText().trim();
String pais = txtPais.getText().trim();
String ciudad = txtCiudad.getText().trim();
String descripcion = txtDescripcion.getText().trim();
String clima = txtClima.getText().trim();
String idioma = txtIdioma.getText().trim();
String imagen = txtImagen.getText().trim();

if (gestionDestino.modificarDestino(id, nombre, pais, ciudad, descripcion, clima, idioma, imagen)) {
    listarDestinos();
    limpiar();
    javax.swing.JOptionPane.showMessageDialog(this, "Destino modificado correctamente");
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo modificar");
}
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText().trim();       
DestinosTuristicos objDestino = gestionDestino.buscarPorId(id);
if (objDestino != null) {
    txtNombre.setText(objDestino.getNombre());
    txtPais.setText(objDestino.getPais());
    txtCiudad.setText(objDestino.getCiudad());
    txtDescripcion.setText(objDestino.getDescripción()); 
    txtClima.setText(objDestino.getClima());
    txtIdioma.setText(objDestino.getIdioma());
    txtImagen.setText(objDestino.getImagen());       
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el destino");
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(frmDestinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Gestion.GestionDestinoTuristico gestion = new Gestion.GestionDestinoTuristico();
                new frmDestinos(gestion).setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabelCiudad;
    private javax.swing.JLabel jlabelClima;
    private javax.swing.JLabel jlabelDescripcion;
    private javax.swing.JLabel jlabelId;
    private javax.swing.JLabel jlabelIdioma;
    private javax.swing.JLabel jlabelImagen;
    private javax.swing.JLabel jlabelNombre;
    private javax.swing.JLabel jlabelPais;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtClima;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    // End of variables declaration//GEN-END:variables
}
