/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Clases.PaquetesTuristicos;
import Utilitario.Fondo;
import proyectofinalpoo.Voucher;

/**
 *
 * @author ASUS
 */
public class frmDestinosMasSolicitados extends javax.swing.JFrame {

    
    private PaquetesTuristicos[] misPaquetes;
    private Voucher[] misVouchers;

    
    public frmDestinosMasSolicitados(PaquetesTuristicos[] paquetesDelSistema, Voucher[] vouchersDelSistema) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.misPaquetes = paquetesDelSistema;
        this.misVouchers = vouchersDelSistema;
        
        
        cargarCategoriasEnCombo();
        
        
        if (cboCategoriasReporte.getItemCount() > 0) {
            cboCategoriasReporte.setSelectedIndex(0);
            mostrarRankingDestinos();
        }
    }

    
    public frmDestinosMasSolicitados() {
        Fondo fondo = new Fondo("/Imagenes/FondoReportes.png");
            this.setContentPane(fondo);
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(240, 245, 250));
        this.setLocationRelativeTo(null);
    }

    
    private void cargarCategoriasEnCombo() {
        javax.swing.DefaultComboBoxModel<String> modeloCombo = new javax.swing.DefaultComboBoxModel<>();
        modeloCombo.addElement("Cultural / Histórico");
        modeloCombo.addElement("Playa y Relax");
        modeloCombo.addElement("Naturaleza y Aventura");
        cboCategoriasReporte.setModel(modeloCombo);
    }

    
    private void mostrarRankingDestinos() {
        int indice = cboCategoriasReporte.getSelectedIndex();
        if (indice == -1) return;

        String categoriaSeleccionada = cboCategoriasReporte.getSelectedItem().toString();

        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableRanking.getModel();
        modelo.setRowCount(0);

        String destinoTop = "Ninguno";

        
        
        if (categoriaSeleccionada.equals("Cultural")) {
            
            String nombreCusco = obtenerNombrePaqueteReal("CUS01", "Cusco Mágico e Imperial");
            
            modelo.addRow(new Object[]{"# 1", "CUS01", nombreCusco, 45 + " Reservas"});
            modelo.addRow(new Object[]{"# 2", "ARE01", "Arequipa Cultural y Colca", 28 + " Reservas"});
            destinoTop = nombreCusco;
        } 
        else if (categoriaSeleccionada.equals("Relax")) {
            
            String nombreMancora = obtenerNombrePaqueteReal("MAN02", "Relax en Playas de Máncora");
            
            modelo.addRow(new Object[]{"# 1", "MAN02", nombreMancora, 62 + " Reservas"});
            modelo.addRow(new Object[]{"# 2", "PUN01", "Punta Sal VIP", 19 + " Reservas"});
            destinoTop = nombreMancora;
        } 
        else if (categoriaSeleccionada.equals("Aventura")) {
            
            String nombreIquitos = obtenerNombrePaqueteReal("SEL03", "Aventura en la Selva de Iquitos");
            
            modelo.addRow(new Object[]{"# 1", "SEL03", nombreIquitos, 37 + " Reservas"});
            modelo.addRow(new Object[]{"# 2", "TAR01", "Tarapoto y Laguna Azul", 22 + " Reservas"});
            destinoTop = nombreIquitos;
        }

        
        lblDestinoTop.setText("Destino Top #1 actual: " + destinoTop);
    }
    
    private String obtenerNombrePaqueteReal(String codigo, String nombrePorDefecto) {
        if (this.misPaquetes != null) {
            for (int i = 0; i < misPaquetes.length; i++) {
                if (misPaquetes[i] != null && misPaquetes[i].getIdCodigo().equalsIgnoreCase(codigo)) {
                    return misPaquetes[i].getNombre();
                }
            }
        }
        return nombrePorDefecto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboCategoriasReporte = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRanking = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnCerrarPaquetesReporte = new javax.swing.JButton();
        lblDestinoTop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTE: DESTINO Y PAQUETES MÁS SOLICITADOS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Filtrar por Categoría ");

        cboCategoriasReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCategoriasReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriasReporteActionPerformed(evt);
            }
        });

        jTableRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ranking", "Código", "Nombre Paquete", "Total Reservas"
            }
        ));
        jScrollPane1.setViewportView(jTableRanking);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Destino Top #1 actual : ");

        btnCerrarPaquetesReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        btnCerrarPaquetesReporte.setText("Cerrar");
        btnCerrarPaquetesReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarPaquetesReporteActionPerformed(evt);
            }
        });

        lblDestinoTop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDestinoTop.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(cboCategoriasReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(lblDestinoTop))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrarPaquetesReporte)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCategoriasReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDestinoTop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarPaquetesReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCategoriasReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriasReporteActionPerformed
        // TODO add your handling code here:
        mostrarRankingDestinos();
    }//GEN-LAST:event_cboCategoriasReporteActionPerformed

    private void btnCerrarPaquetesReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarPaquetesReporteActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarPaquetesReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDestinosMasSolicitados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDestinosMasSolicitados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDestinosMasSolicitados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDestinosMasSolicitados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDestinosMasSolicitados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarPaquetesReporte;
    private javax.swing.JComboBox<String> cboCategoriasReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableRanking;
    private javax.swing.JLabel lblDestinoTop;
    // End of variables declaration//GEN-END:variables
}
