/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

/**
 *
 * @author ASUS
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        MenubarPrincipal = new javax.swing.JMenuBar();
        mnAdministracion = new javax.swing.JMenu();
        mnitemGestionarEmpleados = new javax.swing.JMenuItem();
        mnitemGestionarDestinos = new javax.swing.JMenuItem();
        mnitemGestionarPaquetes = new javax.swing.JMenuItem();
        mnitemPromocionesDescuentos = new javax.swing.JMenuItem();
        mnVentas = new javax.swing.JMenu();
        mnOperaciones = new javax.swing.JMenu();
        mnitemItinerario = new javax.swing.JMenuItem();
        mnitemCupos = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        mnitemReservasPaquete = new javax.swing.JMenuItem();
        mnitemDestinosSolicitados = new javax.swing.JMenuItem();
        mnitemIngresosPorAsesor = new javax.swing.JMenuItem();
        mnitemClienteconDeuda = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        mnitmCerrarsesion = new javax.swing.JMenuItem();
        mnitmSalir = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnAdministracion.setText("Administración");

        mnitemGestionarEmpleados.setText("Gestionar Empleados");
        mnAdministracion.add(mnitemGestionarEmpleados);

        mnitemGestionarDestinos.setText("Gestionar Destinos");
        mnAdministracion.add(mnitemGestionarDestinos);

        mnitemGestionarPaquetes.setText("Gestionar Paquetes Turísticos");
        mnAdministracion.add(mnitemGestionarPaquetes);

        mnitemPromocionesDescuentos.setText("Promociones y Descuentos ");
        mnAdministracion.add(mnitemPromocionesDescuentos);

        MenubarPrincipal.add(mnAdministracion);

        mnVentas.setText("Ventas");
        MenubarPrincipal.add(mnVentas);

        mnOperaciones.setText("Operaciones");

        mnitemItinerario.setText("Itinerario");
        mnOperaciones.add(mnitemItinerario);

        mnitemCupos.setText("Control de Cupos");
        mnOperaciones.add(mnitemCupos);

        MenubarPrincipal.add(mnOperaciones);

        menuReportes.setText("Reportes");

        mnitemReservasPaquete.setText("Reservas por Paquete");
        menuReportes.add(mnitemReservasPaquete);

        mnitemDestinosSolicitados.setText("Destinos más solicitados");
        menuReportes.add(mnitemDestinosSolicitados);

        mnitemIngresosPorAsesor.setText("Ingresos por Asesor");
        menuReportes.add(mnitemIngresosPorAsesor);

        mnitemClienteconDeuda.setText("Cliente con Deuda");
        menuReportes.add(mnitemClienteconDeuda);

        MenubarPrincipal.add(menuReportes);

        mnSistema.setText("Sistema");

        mnitmCerrarsesion.setText("Cerrar sesión");
        mnSistema.add(mnitmCerrarsesion);

        mnitmSalir.setText("Salir del sistema");
        mnSistema.add(mnitmSalir);

        MenubarPrincipal.add(mnSistema);

        setJMenuBar(MenubarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEmenuAdministracionnull, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenubarPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu mnAdministracion;
    private javax.swing.JMenu mnOperaciones;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenu mnVentas;
    private javax.swing.JMenuItem mnitemClienteconDeuda;
    private javax.swing.JMenuItem mnitemCupos;
    private javax.swing.JMenuItem mnitemDestinosSolicitados;
    private javax.swing.JMenuItem mnitemGestionarDestinos;
    private javax.swing.JMenuItem mnitemGestionarEmpleados;
    private javax.swing.JMenuItem mnitemGestionarPaquetes;
    private javax.swing.JMenuItem mnitemIngresosPorAsesor;
    private javax.swing.JMenuItem mnitemItinerario;
    private javax.swing.JMenuItem mnitemPromocionesDescuentos;
    private javax.swing.JMenuItem mnitemReservasPaquete;
    private javax.swing.JMenuItem mnitmCerrarsesion;
    private javax.swing.JMenuItem mnitmSalir;
    // End of variables declaration//GEN-END:variables
}
