/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Clases.PaquetesTuristicos;
import Gestion.GestionDestinoTuristico;
import Gestion.GestionPaquetesTuristicos;
import Utilitario.Fondo;
import proyectofinalpoo.Voucher;


/**
 *
 * @author ASUS
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    private String rolUsuario;
    private PaquetesTuristicos[] misPaquetes;
    
    private Voucher[] misVouchers = new Voucher[100];
    private int contadorVouchers = 0; 
    /**
     * Creates new form frmPrincipal
     * @param rol
     */
    public frmPrincipal(String rol) {
        
        Fondo fondo = new Fondo("/Imagenes/FondoPrincipal.jpg");
        this.setContentPane(fondo);
        
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.rolUsuario = rol;
        this.getContentPane().setBackground(new java.awt.Color(240, 245, 250));
        
        this.misPaquetes = GestionPaquetesTuristicos.cargarDatosDePrueba();
        aplicarPermisosPorRol();
        
        this.setLocationRelativeTo(null);
        
    }
    private void aplicarPermisosPorRol() {
    if (rolUsuario.equals("Asesor de Viaje")) {
        mnAdministracion.setVisible(false);
        mnOperaciones.setVisible(false);
    } 
    else if (rolUsuario.equals("Operador")) {
        mnAdministracion.setVisible(false);
        mnVentas.setVisible(false);
        menuReportes.setVisible(false);
    }
 }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        MenubarPrincipal = new javax.swing.JMenuBar();
        mnAdministracion = new javax.swing.JMenu();
        mnitemGestionarEmpleados = new javax.swing.JMenuItem();
        mnitemGestionarDestinos = new javax.swing.JMenuItem();
        mnVentas = new javax.swing.JMenu();
        mnOperaciones = new javax.swing.JMenu();
        mnitemItinerario = new javax.swing.JMenuItem();
        mnitemCupos = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        mnitemReservasPaquete = new javax.swing.JMenuItem();
        mnitemDestinosSolicitados = new javax.swing.JMenuItem();
        mnitemIngresosPorAsesor = new javax.swing.JMenuItem();
        mnitemClienteconDeuda = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        mnitmCerrarsesion = new javax.swing.JMenuItem();
        mnitmSalir = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEGACY TRAVEL - MENÚ PRINCIPAL");

        mnAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gerente.png"))); // NOI18N
        mnAdministracion.setText("Administración");

        mnitemGestionarEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado-del-mes.png"))); // NOI18N
        mnitemGestionarEmpleados.setText("Gestionar Empleados");
        mnitemGestionarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemGestionarEmpleadosActionPerformed(evt);
            }
        });
        mnAdministracion.add(mnitemGestionarEmpleados);

        mnitemGestionarDestinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapa.png"))); // NOI18N
        mnitemGestionarDestinos.setText("Gestionar Destinos");
        mnitemGestionarDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemGestionarDestinosActionPerformed(evt);
            }
        });
        mnAdministracion.add(mnitemGestionarDestinos);

        MenubarPrincipal.add(mnAdministracion);

        mnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas.png"))); // NOI18N
        mnVentas.setText("Ventas");
        mnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnVentasMouseClicked(evt);
            }
        });
        MenubarPrincipal.add(mnVentas);

        mnOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sistemas.png"))); // NOI18N
        mnOperaciones.setText("Operaciones");

        mnitemItinerario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/itinerario.png"))); // NOI18N
        mnitemItinerario.setText("Itinerario");
        mnitemItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemItinerarioActionPerformed(evt);
            }
        });
        mnOperaciones.add(mnitemItinerario);

        mnitemCupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cupon-de-descuento.png"))); // NOI18N
        mnitemCupos.setText("Control de Cupos");
        mnitemCupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemCuposActionPerformed(evt);
            }
        });
        mnOperaciones.add(mnitemCupos);

        MenubarPrincipal.add(mnOperaciones);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inmigracion.png"))); // NOI18N
        menuReportes.setText("Reportes");

        mnitemReservasPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pquete.png"))); // NOI18N
        mnitemReservasPaquete.setText("Reservas por Paquete");
        mnitemReservasPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemReservasPaqueteActionPerformed(evt);
            }
        });
        menuReportes.add(mnitemReservasPaquete);

        mnitemDestinosSolicitados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/destino.png"))); // NOI18N
        mnitemDestinosSolicitados.setText("Destinos más solicitados");
        mnitemDestinosSolicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemDestinosSolicitadosActionPerformed(evt);
            }
        });
        menuReportes.add(mnitemDestinosSolicitados);

        mnitemIngresosPorAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresos.png"))); // NOI18N
        mnitemIngresosPorAsesor.setText("Ingresos por Asesor");
        mnitemIngresosPorAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemIngresosPorAsesorActionPerformed(evt);
            }
        });
        menuReportes.add(mnitemIngresosPorAsesor);

        mnitemClienteconDeuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Deuda.png"))); // NOI18N
        mnitemClienteconDeuda.setText("Cliente con Deuda");
        mnitemClienteconDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemClienteconDeudaActionPerformed(evt);
            }
        });
        menuReportes.add(mnitemClienteconDeuda);

        MenubarPrincipal.add(menuReportes);

        mnSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sistema-de-escritorio.png"))); // NOI18N
        mnSistema.setText("Sistema");

        mnitmCerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        mnitmCerrarsesion.setText("Cerrar sesión");
        mnitmCerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmCerrarsesionActionPerformed(evt);
            }
        });
        mnSistema.add(mnitmCerrarsesion);

        mnitmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SalirSistema.png"))); // NOI18N
        mnitmSalir.setText("Salir del sistema");
        mnitmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmSalirActionPerformed(evt);
            }
        });
        mnSistema.add(mnitmSalir);

        MenubarPrincipal.add(mnSistema);

        setJMenuBar(MenubarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmSalirActionPerformed
                                          
   
    final javax.swing.JDialog ventanaAlerta = new javax.swing.JDialog(this, "Saliendo", true);
    
    
    ventanaAlerta.setUndecorated(true);
    
    
    javax.swing.JLabel txtMensaje = new javax.swing.JLabel(
        "<html><center><font size='5' color='#0f2a4a'><b>Legacy Travel</b></font><br>"
        + "<font size='4' color='#555555'>Cerrando el sistema de forma segura...<br>Espere un momento.</font></center></html>", 
        javax.swing.JLabel.CENTER
    );
    
    
    txtMensaje.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30));
    ventanaAlerta.getContentPane().setBackground(java.awt.Color.WHITE);
    ventanaAlerta.getContentPane().add(txtMensaje);
    
    
    ((javax.swing.JComponent)ventanaAlerta.getContentPane()).setBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1)
    );

    
    ventanaAlerta.pack();
    ventanaAlerta.setLocationRelativeTo(this);

    
    javax.swing.Timer temporizador = new javax.swing.Timer(3000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            ventanaAlerta.dispose(); 
            System.exit(0);         
        }
    });
    temporizador.setRepeats(false);
    temporizador.start(); 

   
    ventanaAlerta.setVisible(true);
    }//GEN-LAST:event_mnitmSalirActionPerformed

    private void mnitmCerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmCerrarsesionActionPerformed
        // TODO add your handling code here:
        // 1. Creamos la ventana emergente flotante (JDialog) vinculada al formulario principal
        final javax.swing.JDialog alertaCierre = new javax.swing.JDialog(this, "Cerrando Sesión", true);
        
        // 2. Le quitamos los bordes y la 'X' para que se vea minimalista
        alertaCierre.setUndecorated(true);

        // 3. Diseñamos el mensaje elegante en HTML
        javax.swing.JLabel txtMensaje = new javax.swing.JLabel(
            "<html><center><font size='5' color='#0f2a4a'><b>Legacy Travel</b></font><br>"
            + "<font size='4' color='#555555'>Cerrando sesión de forma segura...<br>Redireccionando al Login.</font></center></html>", 
            javax.swing.JLabel.CENTER
        );

        // 4. Configuramos el contenedor (Fondo blanco, márgenes y borde fino gris)
        txtMensaje.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30));
        alertaCierre.getContentPane().setBackground(java.awt.Color.WHITE);
        alertaCierre.getContentPane().add(txtMensaje);

        ((javax.swing.JComponent)alertaCierre.getContentPane()).setBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1)
        );

        
        alertaCierre.pack();
        alertaCierre.setLocationRelativeTo(this);

        
        this.setVisible(false);

        
        javax.swing.Timer temporizador = new javax.swing.Timer(3000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                alertaCierre.dispose();      
                frmPrincipal.this.dispose(); 
                
                
                frmLogin ventanaLogin = new frmLogin();
                ventanaLogin.setVisible(true);
                ventanaLogin.setLocationRelativeTo(null);
            }
        });
        
        temporizador.setRepeats(false);
        temporizador.start(); 

        
        alertaCierre.setVisible(true);   
    }//GEN-LAST:event_mnitmCerrarsesionActionPerformed

    private void mnitemReservasPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemReservasPaqueteActionPerformed
        // TODO add your handling code here:
        
        frmReservaPorPaquetes ventanaReporte = new frmReservaPorPaquetes(this.misPaquetes, this.misVouchers);
        ventanaReporte.setVisible(true);
    }//GEN-LAST:event_mnitemReservasPaqueteActionPerformed

    private void mnitemItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemItinerarioActionPerformed
        // TODO add your handling code here:
       
        if (this.misPaquetes == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El sistema de paquetes no está inicializado.", 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        frmItinerario ventanaItinerario = new frmItinerario(this.misPaquetes);
        
        
        ventanaItinerario.setVisible(true);
    }//GEN-LAST:event_mnitemItinerarioActionPerformed

    private void mnitemCuposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemCuposActionPerformed
        // TODO add your handling code here:
        
        frmCupos ventanaCupos = new frmCupos(this.misPaquetes);
        ventanaCupos.setVisible(true);
    }//GEN-LAST:event_mnitemCuposActionPerformed

    private void mnitemDestinosSolicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemDestinosSolicitadosActionPerformed
        // TODO add your handling code here:
        frmDestinosMasSolicitados ventanaDestinos = new frmDestinosMasSolicitados(this.misPaquetes, this.misVouchers);
        ventanaDestinos.setVisible(true);
    }//GEN-LAST:event_mnitemDestinosSolicitadosActionPerformed

    private void mnitemIngresosPorAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemIngresosPorAsesorActionPerformed
        frmReporteIngresosAsesor ventanaAsesores = new frmReporteIngresosAsesor(this.misPaquetes, this.misVouchers);
        ventanaAsesores.setVisible(true);
    }//GEN-LAST:event_mnitemIngresosPorAsesorActionPerformed

    private void mnitemClienteconDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemClienteconDeudaActionPerformed
        // TODO add your handling code here:
        frmReporteDeudas ventanaDeudas = new frmReporteDeudas(this.misPaquetes, this.misVouchers);
        ventanaDeudas.setVisible(true);
    }//GEN-LAST:event_mnitemClienteconDeudaActionPerformed

    private void mnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnVentasMouseClicked
        // TODO add your handling code here:
    VentanaVentas winVentas = new VentanaVentas(this.misPaquetes, this.misVouchers);
    winVentas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    winVentas.setLocationRelativeTo(null);
    winVentas.setVisible(true);
    
    }//GEN-LAST:event_mnVentasMouseClicked

    private void mnitemGestionarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemGestionarEmpleadosActionPerformed
        // TODO add your handling code here:
        frmGestionEmpleado ventanaEmp = new frmGestionEmpleado(); 
    ventanaEmp.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    ventanaEmp.setLocationRelativeTo(null);
    ventanaEmp.setVisible(true);
    }//GEN-LAST:event_mnitemGestionarEmpleadosActionPerformed

    private void mnitemGestionarDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemGestionarDestinosActionPerformed
        // TODO add your handling code here:
    Gui.frmDestinos ventanaDest = new Gui.frmDestinos(new GestionDestinoTuristico());
    ventanaDest.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    ventanaDest.setLocationRelativeTo(null);
    ventanaDest.setVisible(true);
    }//GEN-LAST:event_mnitemGestionarDestinosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }//</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal("").setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenubarPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu mnAdministracion;
    private javax.swing.JMenu mnOperaciones;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenu mnVentas;
    private javax.swing.JMenuItem mnitemClienteconDeuda;
    private javax.swing.JMenuItem mnitemCupos;
    private javax.swing.JMenuItem mnitemDestinosSolicitados;
    private javax.swing.JMenuItem mnitemGestionarDestinos;
    private javax.swing.JMenuItem mnitemGestionarEmpleados;
    private javax.swing.JMenuItem mnitemIngresosPorAsesor;
    private javax.swing.JMenuItem mnitemItinerario;
    private javax.swing.JMenuItem mnitemReservasPaquete;
    private javax.swing.JMenuItem mnitmCerrarsesion;
    private javax.swing.JMenuItem mnitmSalir;
    // End of variables declaration//GEN-END:variables
}

