/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Clases.PaquetesTuristicos;
import Utilitario.Fondo;
import proyectofinalpoo.Voucher;

/**
 *
 * @author ASUS
 */
public class frmReporteIngresosAsesor extends javax.swing.JFrame {

    /**
     * Creates new form frmReporteIngresosVentasAsesor
     */
    
    private PaquetesTuristicos[] misPaquetes;
    private Voucher[] misVouchers;

    
    public frmReporteIngresosAsesor(PaquetesTuristicos[] paquetesDelSistema, Voucher[] vouchersDelSistema) {
        initComponents();
        this.setLocationRelativeTo(null); 
        
        this.misPaquetes = paquetesDelSistema;
        this.misVouchers = vouchersDelSistema;
        
        
        cargarAsesoresEnCombo();
        
        
        if (cboAsesores.getItemCount() > 0) {
            cboAsesores.setSelectedIndex(0);
            mostrarIngresosAsesor();
        }
    }
    public frmReporteIngresosAsesor() {
        Fondo fondo = new Fondo("/Imagenes/FondoReportes.png");
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(240, 245, 250));
    }
    
    private void cargarAsesoresEnCombo() {
        javax.swing.DefaultComboBoxModel<String> modeloCombo = new javax.swing.DefaultComboBoxModel<>();
        modeloCombo.addElement("ASE-01 - Carlos Mendoza");
        modeloCombo.addElement("ASE-02 - Ana López");
        modeloCombo.addElement("ASE-03 - Luis Castro");
        cboAsesores.setModel(modeloCombo);
    }

    
    private void mostrarIngresosAsesor() {
        int indice = cboAsesores.getSelectedIndex();
        if (indice == -1) return;

        String asesorSeleccionado = cboAsesores.getSelectedItem().toString();

        // Obtenemos el modelo de tu JTable
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableAsesores.getModel();
        modelo.setRowCount(0);

        double montoTotalRecaudado = 0;

        
        double precioBaseCusco = obtenerPrecioPaqueteReal("CUS01", 1200.0);
        double precioBaseMancora = obtenerPrecioPaqueteReal("MAN02", 850.0);

        
        if (asesorSeleccionado.contains("Carlos Mendoza")) {
            double venta1 = 2 * precioBaseCusco;
            double venta2 = 1 * precioBaseMancora;
            
            modelo.addRow(new Object[]{"12/07/2026", "VOU-001", "Cusco Mágico (2 Pax)", "S/. " + venta1});
            modelo.addRow(new Object[]{"13/07/2026", "VOU-006", "Máncora Express (1 Pax)", "S/. " + venta2});
            montoTotalRecaudado = venta1 + venta2;
        } 
        else if (asesorSeleccionado.contains("Ana López")) {
            double venta1 = 4 * precioBaseMancora;
            
            modelo.addRow(new Object[]{"10/07/2026", "VOU-002", "Máncora Playero (4 Pax)", "S/. " + venta1});
            montoTotalRecaudado = venta1;
        } 
        else if (asesorSeleccionado.contains("Luis Castro")) {
            double precioBaseIquitos = obtenerPrecioPaqueteReal("IQU03", 950.0);
            double venta1 = 3 * precioBaseIquitos;
            
            modelo.addRow(new Object[]{"11/07/2026", "VOU-005", "Iquitos Aventura (3 Pax)", "S/. " + venta1});
            montoTotalRecaudado = venta1;
        }

       
        lblMontoTotalAsesor.setText("MONTO TOTAL RECAUDADO POR ESTE ASESOR: S/. " + montoTotalRecaudado);
    }

    
    private double obtenerPrecioPaqueteReal(String codigo, double precioPorDefecto) {
        if (this.misPaquetes != null) {
            for (int i = 0; i < misPaquetes.length; i++) {
                if (misPaquetes[i] != null && misPaquetes[i].getIdCodigo().equalsIgnoreCase(codigo)) {
                    return misPaquetes[i].getPrecioPorPersona(); 
                }
            }
        }
        return precioPorDefecto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboAsesores = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAsesores = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        btnCerrarIngresoAsesor = new javax.swing.JButton();
        lblMontoTotalAsesor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTE DE ASESORES");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Seleccionar Asesor: ");

        cboAsesores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAsesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAsesoresActionPerformed(evt);
            }
        });

        jTableAsesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha Venta", "N° Voucher", "Paquete Vendido", "Monto Cobrado"
            }
        ));
        jScrollPane1.setViewportView(jTableAsesores);

        btnCerrarIngresoAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        btnCerrarIngresoAsesor.setText("Cerrar");
        btnCerrarIngresoAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarIngresoAsesorActionPerformed(evt);
            }
        });

        lblMontoTotalAsesor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMontoTotalAsesor.setText("MONTO TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42)
                                .addComponent(cboAsesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarIngresoAsesor))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMontoTotalAsesor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboAsesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMontoTotalAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCerrarIngresoAsesor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboAsesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAsesoresActionPerformed
        // TODO add your handling code here:
        mostrarIngresosAsesor(); 
    }//GEN-LAST:event_cboAsesoresActionPerformed

    private void btnCerrarIngresoAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarIngresoAsesorActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarIngresoAsesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteIngresosAsesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteIngresosAsesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteIngresosAsesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteIngresosAsesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteIngresosAsesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarIngresoAsesor;
    private javax.swing.JComboBox<String> cboAsesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableAsesores;
    private javax.swing.JLabel lblMontoTotalAsesor;
    // End of variables declaration//GEN-END:variables
}
