/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Clases.PaquetesTuristicos;
import Utilitario.Fondo;
import proyectofinalpoo.Voucher;

/**
 *
 * @author ASUS
 */
public class frmReporteDeudas extends javax.swing.JFrame {

    
    private PaquetesTuristicos[] misPaquetes;
    private Voucher[] misVouchers;

   
    public frmReporteDeudas(PaquetesTuristicos[] paquetesDelSistema, Voucher[] vouchersDelSistema) {
        initComponents();
        this.setLocationRelativeTo(null); 
        
        
        this.misPaquetes = paquetesDelSistema;
        this.misVouchers = vouchersDelSistema;
        
        
        mostrarClientesConDeuda(false);
    }

    
    public frmReporteDeudas() {
        Fondo fondo = new Fondo("/Imagenes/FondoReportes.png");
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(240, 245, 250));
    }

    
    private void mostrarClientesConDeuda(boolean soloMayoresA100) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableDeudas.getModel();
        modelo.setRowCount(0); // Limpiar filas anteriores

        double totalDineroPendienteCobro = 0;

        
        
        double total1 = 2400.0, pagado1 = 2000.0, deuda1 = total1 - pagado1;
        if (!soloMayoresA100 || deuda1 > 100.0) {
            modelo.addRow(new Object[]{"45889922", "Pedro Alcántara Solís", "987654321", "S/. " + total1, "S/. " + pagado1, "S/. " + deuda1});
            totalDineroPendienteCobro += deuda1;
        }

        
        double total2 = 850.0, pagado2 = 800.0, deuda2 = total2 - pagado2; 
        if (!soloMayoresA100 || deuda2 > 100.0) {
            modelo.addRow(new Object[]{"70112233", "Milagros Vega Luna", "941258763", "S/. " + total2, "S/. " + pagado2, "S/. " + deuda2});
            totalDineroPendienteCobro += deuda2;
        }

        
        double total3 = 1900.0, pagado3 = 1200.0, deuda3 = total3 - pagado3; 
        if (!soloMayoresA100 || deuda3 > 100.0) {
            modelo.addRow(new Object[]{"09556622", "Roberto Gómez Wong", "963258147", "S/. " + total3, "S/. " + pagado3, "S/. " + deuda3});
            totalDineroPendienteCobro += deuda3;
        }

       
        lblTotalPendiente.setText("Total Dinero Pendiente de Cobro en el Sistema: S/. " + totalDineroPendienteCobro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chbDeudasMayores = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDeudas = new javax.swing.JTable();
        lblTotalPendiente = new javax.swing.JLabel();
        btnCerrarDeuda = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTE DE CLIENTES CON SALDO PENDIENTE");

        chbDeudasMayores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chbDeudasMayores.setText("Mostrar solo deudas mayores a S/100.00");
        chbDeudasMayores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbDeudasMayoresActionPerformed(evt);
            }
        });

        jTableDeudas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI Cliente", "Nombre Pasajero", "Teléfono", "Total", "Pagado", "Deuda"
            }
        ));
        jScrollPane1.setViewportView(jTableDeudas);

        lblTotalPendiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPendiente.setText("Pendiente");

        btnCerrarDeuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        btnCerrarDeuda.setText("Cerrar");
        btnCerrarDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarDeudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btnCerrarDeuda)
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbDeudasMayores)
                        .addGap(28, 132, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalPendiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(chbDeudasMayores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalPendiente)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarDeuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbDeudasMayoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDeudasMayoresActionPerformed
        // TODO add your handling code here:
        
        boolean filtrar = chbDeudasMayores.isSelected();
        mostrarClientesConDeuda(filtrar);
    }//GEN-LAST:event_chbDeudasMayoresActionPerformed

    private void btnCerrarDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarDeudaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarDeudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteDeudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteDeudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteDeudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteDeudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteDeudas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarDeuda;
    private javax.swing.JCheckBox chbDeudasMayores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableDeudas;
    private javax.swing.JLabel lblTotalPendiente;
    // End of variables declaration//GEN-END:variables
}
