/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Clases.PaquetesTuristicos;
import javax.swing.table.DefaultTableModel;
import proyectofinalpoo.Cliente;
import proyectofinalpoo.Fidelizacion;
import proyectofinalpoo.Pago;
import proyectofinalpoo.Promocion;
import proyectofinalpoo.Reserva;
import proyectofinalpoo.Voucher;

/**
 *
 * @author jahzeelp
 */
public class VentanaVentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaVentas.class.getName());

    /**
     * Creates new form VentanaVentas
     */
    DefaultTableModel model;
    Reserva[] reservas = new Reserva[50];
    int cantidadReservas = 0;
    
    
    private PaquetesTuristicos[] paquetes; 
    private Voucher[] vouchers;            
    
    int cantidadPaquetes = 0;
    
    Cliente[] clientes = new Cliente[50];
    int cantidadClientes = 0;

    DefaultTableModel modelClientes;
    
    Fidelizacion fidelizacion = new Fidelizacion();



   public VentanaVentas(PaquetesTuristicos[] paquetesRecibidos, Voucher[] vouchersRecibidos) {
        initComponents();
        this.paquetes = paquetesRecibidos;
        this.vouchers = vouchersRecibidos;
        
        
        if (this.paquetes != null) {
            this.cantidadPaquetes = this.paquetes.length;
        }
        
        model = new DefaultTableModel();
        model.addColumn("Código Reserva");
        model.addColumn("Monto");
        model.addColumn("Método de Pago");
        this.jTPagos.setModel(model);
        
        modelClientes = new DefaultTableModel();
        modelClientes.addColumn("DNI");
        modelClientes.addColumn("Nombres");
        modelClientes.addColumn("Apellidos");
        modelClientes.addColumn("Teléfono");
        modelClientes.addColumn("Correo");
        this.NTablaClientes.setModel(modelClientes);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        RegistroClientes = new java.awt.Panel();
        Rdni = new javax.swing.JTextField();
        RDni = new javax.swing.JLabel();
        RNombres = new javax.swing.JLabel();
        Rnombres = new javax.swing.JTextField();
        RApellidos = new javax.swing.JLabel();
        Rapellidos = new javax.swing.JTextField();
        RTelefono = new javax.swing.JLabel();
        Rtelefono = new javax.swing.JTextField();
        RCorreo = new javax.swing.JLabel();
        Rcorreo = new javax.swing.JTextField();
        RregistrarCliente = new javax.swing.JButton();
        RClientes = new javax.swing.JScrollPane();
        NTablaClientes = new javax.swing.JTable();
        NumeroReservas = new java.awt.Panel();
        NCodigoPaquete = new javax.swing.JLabel();
        NCodigo = new javax.swing.JTextField();
        NCantidadAdultos = new javax.swing.JLabel();
        NAdultos = new javax.swing.JTextField();
        NCantidadMenores = new javax.swing.JLabel();
        NCrearReserva = new javax.swing.JButton();
        NMenores = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        NAreaVoucher = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        NNombreCliente = new javax.swing.JTextField();
        GestionPagos = new java.awt.Panel();
        jLReservas = new javax.swing.JLabel();
        CodigoReserva = new javax.swing.JTextField();
        jLMontoPagar = new javax.swing.JLabel();
        Monto = new javax.swing.JTextField();
        JEfectivo = new javax.swing.JRadioButton();
        JTarjeta = new javax.swing.JRadioButton();
        Tabla = new javax.swing.JScrollPane();
        jTPagos = new javax.swing.JTable();
        JTransferencia = new javax.swing.JRadioButton();
        JRegistrarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Rdni.addActionListener(this::RdniActionPerformed);

        RDni.setText("DNI");

        RNombres.setText("Nombres");

        RApellidos.setText("Apellidos");

        RTelefono.setText("Telefono");

        RCorreo.setText("Correo");

        RregistrarCliente.setText("Registrar Cliente");
        RregistrarCliente.addActionListener(this::RregistrarClienteActionPerformed);

        NTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        RClientes.setViewportView(NTablaClientes);

        javax.swing.GroupLayout RegistroClientesLayout = new javax.swing.GroupLayout(RegistroClientes);
        RegistroClientes.setLayout(RegistroClientesLayout);
        RegistroClientesLayout.setHorizontalGroup(
            RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroClientesLayout.createSequentialGroup()
                .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroClientesLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RegistroClientesLayout.createSequentialGroup()
                                .addComponent(RApellidos)
                                .addGap(18, 18, 18)
                                .addComponent(Rapellidos))
                            .addGroup(RegistroClientesLayout.createSequentialGroup()
                                .addComponent(RNombres)
                                .addGap(18, 18, 18)
                                .addComponent(Rnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistroClientesLayout.createSequentialGroup()
                                .addComponent(RDni)
                                .addGap(52, 52, 52)
                                .addComponent(Rdni, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistroClientesLayout.createSequentialGroup()
                                .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RTelefono)
                                    .addComponent(RCorreo))
                                .addGap(18, 18, 18)
                                .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rcorreo)
                                    .addGroup(RegistroClientesLayout.createSequentialGroup()
                                        .addComponent(Rtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(RregistrarCliente)))
                    .addGroup(RegistroClientesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(RClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        RegistroClientesLayout.setVerticalGroup(
            RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroClientesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RNombres)
                    .addComponent(Rnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RApellidos)
                    .addComponent(Rapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RTelefono)
                    .addComponent(Rtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RCorreo)
                    .addComponent(Rcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RregistrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Registro de Clientes", RegistroClientes);

        NCodigoPaquete.setText("Codigo de Paquete");

        NCantidadAdultos.setText("Cantidad de adultos");

        NCantidadMenores.setText("Cantidad de Menores");

        NCrearReserva.setText("Generar Voucher");
        NCrearReserva.addActionListener(this::NCrearReservaActionPerformed);

        NAreaVoucher.setColumns(20);
        NAreaVoucher.setRows(5);
        jScrollPane1.setViewportView(NAreaVoucher);

        jLabel2.setText("Nombre del Cliente");

        NNombreCliente.addActionListener(this::NNombreClienteActionPerformed);

        javax.swing.GroupLayout NumeroReservasLayout = new javax.swing.GroupLayout(NumeroReservas);
        NumeroReservas.setLayout(NumeroReservasLayout);
        NumeroReservasLayout.setHorizontalGroup(
            NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumeroReservasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NCrearReserva)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NumeroReservasLayout.createSequentialGroup()
                        .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NumeroReservasLayout.createSequentialGroup()
                                    .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NCodigoPaquete)
                                        .addComponent(NCantidadAdultos))
                                    .addGap(25, 25, 25))
                                .addGroup(NumeroReservasLayout.createSequentialGroup()
                                    .addComponent(NCantidadMenores)
                                    .addGap(18, 18, 18)))
                            .addGroup(NumeroReservasLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)))
                        .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NMenores, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NAdultos, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        NumeroReservasLayout.setVerticalGroup(
            NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumeroReservasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NCodigoPaquete)
                    .addComponent(NCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NCantidadAdultos)
                    .addComponent(NAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NumeroReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NCantidadMenores)
                    .addComponent(NMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(NCrearReserva)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nueva Reserva\\Voucher", NumeroReservas);

        jLReservas.setText("Codigo de Reservas");

        jLMontoPagar.setText("Monto a Pagar");

        Monto.addActionListener(this::MontoActionPerformed);

        buttonGroup1.add(JEfectivo);
        JEfectivo.setText("Efectivo");
        JEfectivo.addActionListener(this::JEfectivoActionPerformed);

        buttonGroup1.add(JTarjeta);
        JTarjeta.setText("Tarjeta");
        JTarjeta.addActionListener(this::JTarjetaActionPerformed);

        jTPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla.setViewportView(jTPagos);

        buttonGroup1.add(JTransferencia);
        JTransferencia.setText("Transferencia");
        JTransferencia.addActionListener(this::JTransferenciaActionPerformed);

        JRegistrarPago.setText("Registrar Pago");
        JRegistrarPago.addActionListener(this::JRegistrarPagoActionPerformed);

        javax.swing.GroupLayout GestionPagosLayout = new javax.swing.GroupLayout(GestionPagos);
        GestionPagos.setLayout(GestionPagosLayout);
        GestionPagosLayout.setHorizontalGroup(
            GestionPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionPagosLayout.createSequentialGroup()
                .addGroup(GestionPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestionPagosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(GestionPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(GestionPagosLayout.createSequentialGroup()
                                .addComponent(jLMontoPagar)
                                .addGap(41, 41, 41)
                                .addComponent(Monto))
                            .addGroup(GestionPagosLayout.createSequentialGroup()
                                .addComponent(jLReservas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(GestionPagosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(JEfectivo)
                        .addGap(40, 40, 40)
                        .addComponent(JTarjeta)
                        .addGap(42, 42, 42)
                        .addComponent(JTransferencia))
                    .addGroup(GestionPagosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(GestionPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRegistrarPago)
                            .addComponent(Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        GestionPagosLayout.setVerticalGroup(
            GestionPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GestionPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLReservas)
                    .addComponent(CodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GestionPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMontoPagar)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GestionPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JEfectivo)
                    .addComponent(JTarjeta)
                    .addComponent(JTransferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(JRegistrarPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        jTabbedPane1.addTab("Gestión de Pagos", GestionPagos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Registro de Clientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JEfectivoActionPerformed

    private void JTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTransferenciaActionPerformed

    private void MontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoActionPerformed

    private void JRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRegistrarPagoActionPerformed
        String codigoReserva = CodigoReserva.getText();
    double monto = Double.parseDouble(Monto.getText());
    String metodo = "Efectivo";
    if (JTarjeta.isSelected()) {
        metodo = "Tarjeta";
    }
    if (JTransferencia.isSelected()) {
        metodo = "Transferencia";
    }
    Reserva reservaEncontrada = null;
    for (int i = 0; i < cantidadReservas; i++) {
        if (reservas[i].getCodigoReserva().equals(codigoReserva)) {
            reservaEncontrada = reservas[i];
        }
    }
    if (reservaEncontrada != null) {
        Pago pago = new Pago("PAG" + codigoReserva, "2026-07-15", monto, metodo);
        reservaEncontrada.registrarPago(pago);
        boolean confirmada = reservaEncontrada.confirmarReserva();
        String[] datos = new String[3];
        datos[0] = codigoReserva;
        datos[1] = String.valueOf(monto);
        datos[2] = metodo;
        model.addRow(datos);
        CodigoReserva.setText(null);
        Monto.setText(null);

        if (confirmada) {
            Cliente clientePrincipal = reservaEncontrada.getClientes()[0];
            String identificador = clientePrincipal.getNombres() + " " + clientePrincipal.getApellidos();

            fidelizacion.agregarPuntos(identificador, reservaEncontrada.getPrecioTotal());

            Promocion descuentoPremio = fidelizacion.generarDescuentoSiAplica(identificador);

            String mensajeExtra = "";
            if (descuentoPremio != null) {
                mensajeExtra = "\n\n¡Felicidades! El cliente alcanzó "
                        + fidelizacion.consultarPuntos(identificador)
                        + " puntos y desbloqueó 10% de descuento en su próxima reserva.";
            }

            Voucher voucher = new Voucher("VCH" + codigoReserva, reservaEncontrada);
            NAreaVoucher.setText(voucher.generarVoucher() + mensajeExtra);
        }
    }
    }//GEN-LAST:event_JRegistrarPagoActionPerformed

    private void JTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTarjetaActionPerformed

    private void NCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NCrearReservaActionPerformed
        // TODO add your handling code here:
        String codigoPaquete = NCodigo.getText(); 
        int adultos = 0;
        int menores = 0;
        
        try {
            adultos = Integer.parseInt(NAdultos.getText());
            menores = Integer.parseInt(NMenores.getText());
        } catch (NumberFormatException e) {
            NAreaVoucher.setText("Error: Ingrese números válidos en adultos y menores.");
            return;
        }
        
        String nombreCliente = NNombreCliente.getText();

        Clases.PaquetesTuristicos paqueteEncontrado = null; 
        if (paquetes != null) {
            for (int i = 0; i < cantidadPaquetes; i++) {
                if (paquetes[i] != null && paquetes[i].getIdCodigo().equals(codigoPaquete)) {
                    paqueteEncontrado = paquetes[i];
                    break;
                }
            }
        }

        Cliente clienteEncontrado = null;
        if (clientes != null) {
            for (int i = 0; i < cantidadClientes; i++) {
                if (clientes[i] != null && clientes[i].getNombres().equalsIgnoreCase(nombreCliente)) {
                    clienteEncontrado = clientes[i];
                    break;
                }
            }
        }

        if (paqueteEncontrado != null && clienteEncontrado != null) {
            String codigoReserva = "RES" + (cantidadReservas + 1);
            
            proyectofinalpoo.PaqueteTuristico paqueteCast = (proyectofinalpoo.PaqueteTuristico) (Object) paqueteEncontrado;
            
            Reserva nuevaReserva = new Reserva(codigoReserva, "2026-07-15", paqueteCast, adultos, menores);
            nuevaReserva.agregarCliente(clienteEncontrado);

            double total = nuevaReserva.calcularTotal();
            reservas[cantidadReservas] = nuevaReserva;
            cantidadReservas++;

            NAreaVoucher.setText("Reserva creada: " + codigoReserva + "\nPrecio total: S/ " + total);
            NCodigo.setText(null);
            NAdultos.setText(null);
            NMenores.setText(null);
            NNombreCliente.setText(null);
        } else if (paqueteEncontrado == null) {
            NAreaVoucher.setText("Paquete no encontrado con el código: " + codigoPaquete);
        } else {
            NAreaVoucher.setText("Cliente no encontrado. Regístralo primero en la pestaña Registro de Clientes.");
        }
    }//GEN-LAST:event_NCrearReservaActionPerformed

    private void RdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdniActionPerformed

    private void RregistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RregistrarClienteActionPerformed
        // TODO add your handling code here
        
        String dni = Rdni.getText();
        String nombres = Rnombres.getText();
        String apellidos = Rapellidos.getText();
        String telefono = Rtelefono.getText();
        String correo = Rcorreo.getText();

        if (nombres.isEmpty() || apellidos.isEmpty()) {
            return;
        }

        Cliente nuevoCliente = new Cliente(nombres, apellidos);

        if (cantidadClientes < clientes.length) {
            clientes[cantidadClientes] = nuevoCliente;
            cantidadClientes++;

            String[] datos = new String[5];
            datos[0] = dni;
            datos[1] = nombres;
            datos[2] = apellidos;
            datos[3] = telefono;
            datos[4] = correo;
            modelClientes.addRow(datos);

            Rdni.setText(null);
            Rnombres.setText(null);
            Rapellidos.setText(null);
            Rtelefono.setText(null);
            Rcorreo.setText(null);
        }
    
    }//GEN-LAST:event_RregistrarClienteActionPerformed

    private void NNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NNombreClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
java.awt.EventQueue.invokeLater(() -> new VentanaVentas(null, null).setVisible(true));    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoReserva;
    private java.awt.Panel GestionPagos;
    private javax.swing.JRadioButton JEfectivo;
    private javax.swing.JButton JRegistrarPago;
    private javax.swing.JRadioButton JTarjeta;
    private javax.swing.JRadioButton JTransferencia;
    private javax.swing.JTextField Monto;
    private javax.swing.JTextField NAdultos;
    private javax.swing.JTextArea NAreaVoucher;
    private javax.swing.JLabel NCantidadAdultos;
    private javax.swing.JLabel NCantidadMenores;
    private javax.swing.JTextField NCodigo;
    private javax.swing.JLabel NCodigoPaquete;
    private javax.swing.JButton NCrearReserva;
    private javax.swing.JTextField NMenores;
    private javax.swing.JTextField NNombreCliente;
    private javax.swing.JTable NTablaClientes;
    private java.awt.Panel NumeroReservas;
    private javax.swing.JLabel RApellidos;
    private javax.swing.JScrollPane RClientes;
    private javax.swing.JLabel RCorreo;
    private javax.swing.JLabel RDni;
    private javax.swing.JLabel RNombres;
    private javax.swing.JLabel RTelefono;
    private javax.swing.JTextField Rapellidos;
    private javax.swing.JTextField Rcorreo;
    private javax.swing.JTextField Rdni;
    private java.awt.Panel RegistroClientes;
    private javax.swing.JTextField Rnombres;
    private javax.swing.JButton RregistrarCliente;
    private javax.swing.JTextField Rtelefono;
    private javax.swing.JScrollPane Tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLMontoPagar;
    private javax.swing.JLabel jLReservas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPagos;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
